<?php

return [
    'campaigns' => [
        [
            'name'         => 'Spring 2026 Player Launch',
            'type'         => 'social',
            'status'       => 'active',
            'start_date'   => '2026-03-01',
            'end_date'     => '2026-06-30',
            'utm_source'   => 'instagram',
            'utm_medium'   => 'social',
            'utm_campaign' => 'spring_players_2026',
            'budget_cents' => 250000,
            'notes'        => 'Demo campaign for CRM dashboard.',
        ],
        [
            'name'         => 'Referral Growth Program',
            'type'         => 'referral',
            'status'       => 'active',
            'start_date'   => '2026-01-01',
            'end_date'     => '2026-12-31',
            'utm_source'   => 'referral',
            'utm_medium'   => 'invite',
            'utm_campaign' => 'member_referrals',
            'budget_cents' => null,
            'notes'        => 'Points-based referral rewards.',
        ],
    ],
    'contacts' => [
        [
            'name'     => 'Alex Müller',
            'email'    => 'alex.mueller@example.com',
            'phone'    => '+49 170 1234567',
            'source'   => 'social',
            'status'   => 'qualified',
            'campaign' => 'Spring 2026 Player Launch',
            'tags'     => ['player_prospect'],
            'notes'    => 'Interested in U21 showcase.',
        ],
        [
            'name'     => 'FC Demo United',
            'email'    => 'scouting@fcdemounited.test',
            'phone'    => '+44 20 7946 0958',
            'source'   => 'event',
            'status'   => 'contacted',
            'campaign' => 'Spring 2026 Player Launch',
            'tags'     => ['club'],
            'notes'    => 'Met at Berlin talent expo.',
        ],
        [
            'name'          => 'Sarah Scout',
            'email'         => 'sarah.scout@example.com',
            'source'        => 'referral',
            'status'        => 'new',
            'campaign'      => 'Referral Growth Program',
            'referral_code' => 'SPORTIFY-DEMO-A1B2',
            'tags'          => ['scout', 'newsletter'],
            'notes'         => 'Referred via invite link.',
        ],
        [
            'name'   => 'Newsletter Lead',
            'email'  => 'fan@example.com',
            'source' => 'website',
            'status' => 'new',
            'tags'   => ['newsletter'],
            'notes'  => 'Signed up on homepage.',
        ],
    ],
];
