<?php
/**
 * Demo sport providers with starter membership plans.
 */

return [
    [
        'slug' => 'ironforge-gym-berlin',
        'type' => 'gym',
        'name' => 'IronForge Gym Berlin',
        'tagline' => 'Strength & conditioning for athletes',
        'description' => 'Performance gym with Olympic lifting platforms, sprint track, and recovery zone. Open to footballers, runners, and team sports.',
        'address' => 'Torstraße 45',
        'city' => 'Berlin',
        'country' => 'Germany',
        'country_code' => 'DE',
        'phone' => '+49 30 1234567',
        'email' => 'hello@ironforge-gym.de',
        'website' => 'https://ironforge-gym.de',
        'data' => ['hours' => 'Mon–Fri 6–22, Sat–Sun 8–20', 'amenities' => ['Sauna', 'Showers', 'Parking']],
        'plans' => [
            ['slug' => 'basic', 'name' => 'Basic Access', 'tagline' => 'Off-peak gym access', 'billing_interval' => 'monthly', 'amount_cents' => 2900, 'visit_credits' => null, 'popular' => false,
             'features' => ['Off-peak access', 'Locker room', '1 guest pass/month']],
            ['slug' => 'unlimited', 'name' => 'Unlimited', 'tagline' => 'Full access anytime', 'billing_interval' => 'monthly', 'amount_cents' => 5900, 'visit_credits' => null, 'popular' => true,
             'features' => ['24/7 access', 'All classes', 'Sauna & recovery', '3 guest passes/month']],
            ['slug' => 'annual', 'name' => 'Annual Unlimited', 'tagline' => 'Best value yearly', 'billing_interval' => 'yearly', 'amount_cents' => 59000, 'visit_credits' => null, 'popular' => false,
             'features' => ['All Unlimited perks', '2 months free', 'Priority booking']],
        ],
    ],
    [
        'slug' => 'zen-touch-massage',
        'type' => 'massage',
        'name' => 'Zen Touch Massage',
        'tagline' => 'Sports massage & deep tissue',
        'description' => 'Licensed therapists specialising in pre-match prep, post-game recovery, and injury prevention massage for athletes.',
        'address' => 'Kurfürstendamm 12',
        'city' => 'Berlin',
        'country' => 'Germany',
        'country_code' => 'DE',
        'phone' => '+49 30 9876543',
        'email' => 'book@zentouch.de',
        'website' => '',
        'data' => ['hours' => 'Tue–Sat 9–19', 'amenities' => ['Private rooms', 'Hot stones', 'Cupping']],
        'plans' => [
            ['slug' => '4-sessions', 'name' => '4 Sessions / mo', 'tagline' => '60-min sports massage', 'billing_interval' => 'monthly', 'amount_cents' => 8000, 'visit_credits' => 4, 'popular' => true,
             'features' => ['4 × 60 min sessions', 'Sports massage', 'Online booking']],
            ['slug' => '8-sessions', 'name' => '8 Sessions / mo', 'tagline' => 'For pro schedules', 'billing_interval' => 'monthly', 'amount_cents' => 14000, 'visit_credits' => 8, 'popular' => false,
             'features' => ['8 × 60 min sessions', 'Priority slots', 'Recovery plan']],
        ],
    ],
    [
        'slug' => 'cairo-recovery-physio',
        'type' => 'physio',
        'name' => 'Cairo Recovery Physio',
        'tagline' => 'Physiotherapy & rehab',
        'description' => 'Football-focused physiotherapy clinic with pitch-side experience. Return-to-play programmes and injury screening.',
        'address' => 'Zamalek District',
        'city' => 'Cairo',
        'country' => 'Egypt',
        'country_code' => 'EG',
        'phone' => '+20 2 555 0100',
        'email' => 'info@cairorecovery.eg',
        'website' => '',
        'data' => ['hours' => 'Sun–Thu 8–20', 'amenities' => ['Hydrotherapy', 'Gym rehab', 'Ultrasound']],
        'plans' => [
            ['slug' => 'rehab-monthly', 'name' => 'Rehab Monthly', 'tagline' => '2 physio sessions + home plan', 'billing_interval' => 'monthly', 'amount_cents' => 4500, 'visit_credits' => 2, 'popular' => true,
             'features' => ['2 physio sessions', 'Home exercise plan', 'WhatsApp support']],
            ['slug' => 'elite-care', 'name' => 'Elite Care', 'tagline' => 'Weekly sessions', 'billing_interval' => 'monthly', 'amount_cents' => 9900, 'visit_credits' => 4, 'popular' => false,
             'features' => ['4 sessions/month', 'Pitch-side referral', 'Nutrition consult']],
        ],
    ],
    [
        'slug' => 'fuel-nutrition-london',
        'type' => 'nutrition',
        'name' => 'Fuel Nutrition London',
        'tagline' => 'Sports nutrition coaching',
        'description' => 'Registered sports dietitians building match-day fueling, cutting weight safely, and hydration plans for academy to pro level.',
        'address' => 'Shoreditch High St',
        'city' => 'London',
        'country' => 'England',
        'country_code' => 'GB',
        'phone' => '+44 20 7946 0958',
        'email' => 'hello@fuelnutrition.co.uk',
        'website' => '',
        'data' => ['hours' => 'Mon–Fri 9–18', 'amenities' => ['Body comp scan', 'Meal plans', 'Supplement review']],
        'plans' => [
            ['slug' => 'starter', 'name' => 'Starter Plan', 'tagline' => 'Monthly meal plan', 'billing_interval' => 'monthly', 'amount_cents' => 3500, 'visit_credits' => 1, 'popular' => false,
             'features' => ['Custom meal plan', '1 video consult/month', 'App tracking']],
            ['slug' => 'pro-fuel', 'name' => 'Pro Fuel', 'tagline' => 'Full coaching', 'billing_interval' => 'monthly', 'amount_cents' => 7500, 'visit_credits' => 2, 'popular' => true,
             'features' => ['Weekly check-ins', 'Match-day protocols', 'Unlimited messaging']],
        ],
    ],
    [
        'slug' => 'flow-yoga-madrid',
        'type' => 'yoga',
        'name' => 'Flow Yoga Madrid',
        'tagline' => 'Mobility & mindfulness',
        'description' => 'Yoga and mobility classes designed for footballers — hip openers, hamstring care, and breath work for match focus.',
        'address' => 'Calle Serrano 88',
        'city' => 'Madrid',
        'country' => 'Spain',
        'country_code' => 'ES',
        'phone' => '+34 91 123 4567',
        'email' => 'studio@flowyoga.es',
        'website' => '',
        'data' => ['hours' => 'Daily 7–21', 'amenities' => ['Mats provided', 'Beginner friendly', 'Team bookings']],
        'plans' => [
            ['slug' => '8-classes', 'name' => '8 Classes', 'tagline' => 'Per month', 'billing_interval' => 'monthly', 'amount_cents' => 4900, 'visit_credits' => 8, 'popular' => true,
             'features' => ['8 studio classes', 'Athlete mobility track', 'Online replays']],
            ['slug' => 'unlimited-yoga', 'name' => 'Unlimited', 'tagline' => 'All classes', 'billing_interval' => 'monthly', 'amount_cents' => 6900, 'visit_credits' => null, 'popular' => false,
             'features' => ['Unlimited classes', '1 private session/quarter', 'Retreat discounts']],
        ],
    ],
    [
        'slug' => 'pulse-recovery-dubai',
        'type' => 'recovery',
        'name' => 'Pulse Recovery Dubai',
        'tagline' => 'Cryo, compression & contrast',
        'description' => 'Elite recovery centre with cryotherapy, NormaTec boots, ice baths, and contrast therapy — trusted by Gulf pro squads.',
        'address' => 'DIFC Gate Village',
        'city' => 'Dubai',
        'country' => 'UAE',
        'country_code' => 'AE',
        'phone' => '+971 4 123 4567',
        'email' => 'book@pulserecovery.ae',
        'website' => '',
        'data' => ['hours' => 'Daily 6–23', 'amenities' => ['Cryo', 'Compression', 'Ice bath']],
        'plans' => [
            ['slug' => 'recovery-pass', 'name' => 'Recovery Pass', 'tagline' => '6 sessions monthly', 'billing_interval' => 'monthly', 'amount_cents' => 12000, 'visit_credits' => 6, 'popular' => true,
             'features' => ['6 recovery sessions', 'Mix cryo & compression', 'Member lounge']],
            ['slug' => 'squad-pack', 'name' => 'Squad Pack', 'tagline' => 'For teams', 'billing_interval' => 'monthly', 'amount_cents' => 45000, 'visit_credits' => 30, 'popular' => false,
             'features' => ['30 team sessions', 'Dedicated slot', 'Travel day package']],
        ],
    ],
];
