<?php
/**
 * Homepage scores marquee — show only high-priority competitions.
 * Matches are kept when competition slug, name, or ESPN season slug matches allowlists.
 */

return [
    /** Max items in the header scores ticker (API may request up to 12). */
    'max_items' => 10,

    /** ESPN feed scopes that bypass generic league-name checks (see LiveFixtureFeedService::LEAGUE_ENDPOINTS). */
    'priority_feed_scopes' => [
        'fifa.world',
        'eng.1',
        'esp.1',
        'ger.1',
        'ita.1',
        'fra.1',
        'uefa.champions',
        'uefa.europa',
    ],

    /** Known competition slugs (from slugForCompetition / competitions table). */
    'allowed_slugs' => [
        'premier-league',
        'la-liga',
        'serie-a',
        'bundesliga',
        'ligue-1',
        'world-cup-2026',
        'ucl-2025-26',
        'uel-2025-26',
        'uecl-2025-26',
        'uefa-euro-2028',
        'fa-cup-2025-26',
        'carabao-cup',
        'copa-del-rey',
        'dfb-pokal',
        'coupe-de-france',
        'coppa-italia',
        'community-shield',
        'super-cup',
        'nations-league',
        'conmebol-libertadores',
        'conmebol-sudamericana',
    ],

    /** Case-insensitive substring match on competition_name. */
    'allowed_names' => [
        'Premier League',
        'La Liga',
        'Serie A',
        'Bundesliga',
        'Ligue 1',
        'FIFA World Cup',
        'World Cup',
        'UEFA Champions League',
        'Champions League',
        'UEFA Europa League',
        'Europa League',
        'UEFA Conference League',
        'Conference League',
        'FA Cup',
        'Carabao Cup',
        'EFL Cup',
        'Copa del Rey',
        'DFB-Pokal',
        'DFB Pokal',
        'Coupe de France',
        'Coppa Italia',
        'Supercopa',
        'Community Shield',
        'Nations League',
        'Libertadores',
        'Sudamericana',
        'Euro 202',
        'European Championship',
    ],

    /** ESPN season.slug fragments — match if contained in stage field. */
    'allowed_stage_patterns' => [
        'premier-league',
        'english-premier',
        'laliga',
        'spanish-laliga',
        'bundesliga',
        'german-bundesliga',
        'serie-a',
        'italian-serie',
        'ligue-1',
        'french-ligue',
        'champions-league',
        'champions',
        'europa-league',
        'europa',
        'conference-league',
        'conference',
        'world-cup',
        'group-stage',
        'fa-cup',
        'carabao',
        'efl-cup',
        'copa-del-rey',
        'dfb-pokal',
        'coupe-de-france',
        'coppa-italia',
        'nations-league',
        'libertadores',
        'sudamericana',
        'euro-202',
    ],

    /** Exclude when stage slug contains any of these (lower-tier / obscure). */
    'blocked_stage_patterns' => [
        'regular-season',
        'first-stage',
        'second-stage',
        'chinese',
        'china',
        'irish',
        'bolivian',
        'brasileiro-serie-b',
        'serie-b',
        'serie-c',
        'usl',
        'mls-next',
        'nwsl',
        'liga-mx',
        'j-league',
        'k-league',
        'a-league',
        'indian-super',
        'saudi-pro',
        'egyptian',
        'colombian',
        'ecuadorian',
        'peruvian',
        'venezuelan',
        'paraguayan',
        'uruguayan',
        'costa-rican',
        'honduran',
        'guatemalan',
        'salvadoran',
        'jamaican',
        'trinidadian',
        'south-african',
        'nigerian',
        'moroccan',
        'tunisian',
        'algerian',
        'romanian',
        'bulgarian',
        'hungarian',
        'czech',
        'slovak',
        'slovenian',
        'croatian',
        'serbian',
        'ukrainian',
        'belarusian',
        'kazakh',
        'uzbek',
        'thai',
        'vietnamese',
        'indonesian',
        'malaysian',
        'singapore',
        'philippine',
        'australian',
        'new-zealand',
    ],

    /** Lower number = higher priority in the ticker. */
    'priority_slugs' => [
        'world-cup-2026' => 0,
        'ucl-2025-26' => 1,
        'uel-2025-26' => 2,
        'uecl-2025-26' => 3,
        'premier-league' => 4,
        'la-liga' => 5,
        'bundesliga' => 6,
        'serie-a' => 7,
        'ligue-1' => 8,
        'fa-cup-2025-26' => 9,
        'carabao-cup' => 10,
        'copa-del-rey' => 11,
        'dfb-pokal' => 12,
        'coupe-de-france' => 13,
        'coppa-italia' => 14,
    ],
];
