<?php
/**
 * Role-based access control (RBAC) configuration.
 *
 * Roles are stored on users.role (VARCHAR). Permissions are checked via Auth::can().
 * super_admin has wildcard access; admin cannot promote users to admin/super_admin.
 */

return [
    /** Map legacy DB role slugs to canonical roles (non-destructive reads). */
    'legacy_aliases' => [],

    'roles' => [
        'super_admin' => [
            'label'               => 'Super Admin',
            'level'               => 100,
            'permissions'         => ['*'],
            'inherits'            => ['admin'],
            'registerable'        => false,
            'home_route'          => 'admin.dashboard',
            'dashboard_redirect'  => 'admin.dashboard',
        ],
        'admin' => [
            'label'               => 'Admin',
            'level'               => 90,
            'inherits'            => [],
            'permissions'         => [
                'admin.access',
                'admin.users',
                'admin.users.view',
                'admin.users.edit',
                'admin.content',
                'admin.settings',
                'competitions.manage',
                'crm.access',
                'crm.manage',
                'referrals.admin',
                'marketplace.admin',
                'marketplace.browse',
                'booking.admin',
                'pro_coaches.admin',
                'transfer_bureau.admin',
                'analysis.regenerate',
                'analysis.health.manage',
                'chatbot.manage_players',
                'chatbot.manage_crm',
                'membership.manage',
                'payment.admin',
                'markt.browse',
            ],
            'registerable'        => false,
            'home_route'          => 'admin.dashboard',
            'dashboard_redirect'  => 'admin.dashboard',
        ],
        'marketing' => [
            'label'               => 'Marketing',
            'level'               => 55,
            'inherits'            => [],
            'permissions'         => [
                'crm.access',
                'crm.manage',
                'referrals.admin',
                'profile.edit',
                'chatbot.manage_crm',
                'markt.browse',
            ],
            'registerable'        => false,
            'home_route'          => 'admin.crm.dashboard',
            'dashboard_redirect'  => 'admin.crm.dashboard',
        ],
        'scout' => [
            'label'               => 'Scout',
            'level'               => 50,
            'inherits'            => [],
            'permissions'         => [
                'scout.access',
                'scout.dashboard',
                'scout.manage_players',
                'scout.shortlist',
                'scout.notes',
                'players.search',
                'players.view',
                'analysis.view',
                'analysis.regenerate',
                'analysis.health.manage',
                'chatbot.manage_players',
                'messages.send',
                'feed.view',
                'feed.post',
                'profile.edit',
                'marketplace.browse',
                'marketplace.sell',
                'fan.create',
                'booking.book',
                'wellness.access',
                'markt.browse',
            ],
            'registerable'        => true,
            'home_route'          => 'scout.dashboard',
            'dashboard_redirect'  => 'scout.dashboard',
        ],
        'club' => [
            'label'               => 'Club',
            'level'               => 50,
            'inherits'            => [],
            'permissions'         => [
                'club.access',
                'club.dashboard',
                'club.recommendations',
                'players.search',
                'players.view',
                'analysis.view',
                'analysis.regenerate',
                'scout.shortlist',
                'messages.send',
                'feed.view',
                'feed.post',
                'profile.edit',
                'marketplace.browse',
                'marketplace.sell',
                'fan.create',
                'booking.book',
                'transfer_bureau.access',
                'transfer_bureau.list',
                'markt.browse',
            ],
            'registerable'        => true,
            'home_route'          => 'club.dashboard',
            'dashboard_redirect'  => 'club.dashboard',
        ],
        'player' => [
            'label'               => 'Player',
            'level'               => 40,
            'inherits'            => [],
            'permissions'         => [
                'player.access',
                'player.profile',
                'player.bookings_receive',
                'players.view',
                'analysis.view',
                'profile.edit',
                'highlights.upload',
                'talent.upload',
                'fitpass.access',
                'wellness.access',
                'predictions.submit',
                'messages.send',
                'feed.view',
                'feed.post',
                'marketplace.browse',
                'marketplace.sell',
                'booking.offer',
                'transfer_bureau.access',
                'transfer_bureau.seek',
                'markt.browse',
            ],
            'registerable'        => true,
            'home_route'          => 'profile.edit',
            'dashboard_redirect'  => 'profile.edit',
        ],
        'trainer' => [
            'label'               => 'Trainer',
            'level'               => 45,
            'inherits'            => [],
            'permissions'         => [
                'trainer.access',
                'trainer.dashboard',
                'trainer.profile',
                'players.view',
                'players.search',
                'profile.edit',
                'messages.send',
                'feed.view',
                'feed.post',
                'marketplace.browse',
                'transfer_bureau.access',
                'transfer_bureau.seek',
                'markt.browse',
            ],
            'registerable'        => true,
            'home_route'          => 'trainer.dashboard',
            'dashboard_redirect'  => 'trainer.dashboard',
        ],
        'provider' => [
            'label'               => 'Provider',
            'level'               => 45,
            'inherits'            => [],
            'permissions'         => [
                'provider.panel',
                'provider.join',
                'profile.edit',
                'messages.send',
                'marketplace.browse',
                'marketplace.sell',
                'pro_coaches.creator',
                'pro_coaches.dashboard',
                'transfer_bureau.access',
                'transfer_bureau.seek',
                'markt.browse',
            ],
            'registerable'        => true,
            'home_route'          => 'pro_coaches.dashboard',
            'dashboard_redirect'  => 'pro_coaches.dashboard',
        ],
        'agent' => [
            'label'               => 'Agent',
            'level'               => 45,
            'inherits'            => ['scout'],
            'permissions'         => [
                'messages.send',
                'feed.view',
                'feed.post',
                'profile.edit',
                'markt.browse',
            ],
            'registerable'        => false,
            'home_route'          => 'scout.dashboard',
            'dashboard_redirect'  => 'scout.dashboard',
        ],
        'coach' => [
            'label'               => 'Coach',
            'level'               => 35,
            'inherits'            => ['provider'],
            'permissions'         => [],
            'registerable'        => false,
            'home_route'          => 'pro_coaches.dashboard',
            'dashboard_redirect'  => 'pro_coaches.dashboard',
        ],
        'company' => [
            'label'               => 'Company',
            'level'               => 30,
            'inherits'            => [],
            'permissions'         => [
                'players.view',
                'analysis.view',
                'profile.edit',
                'feed.view',
                'markt.browse',
            ],
            'registerable'        => false,
            'home_route'          => 'home',
            'dashboard_redirect'  => 'home',
        ],
        'fan' => [
            'label'               => 'Fan',
            'level'               => 10,
            'inherits'            => [],
            'permissions'         => [
                'players.view',
                'analysis.view',
                'profile.edit',
                'feed.view',
                'feed.post',
                'predictions.submit',
                'marketplace.browse',
                'marketplace.sell',
                'fan.create',
                'booking.book',
                'wellness.access',
                'pro_coaches.subscribe',
                'pro_coaches.book',
                'markt.browse',
            ],
            'registerable'        => true,
            'home_route'          => 'membership.role',
            'dashboard_redirect'  => 'membership.role',
            'home_route_params'   => ['role' => 'fan'],
        ],
        'guest' => [
            'label'               => 'Guest',
            'level'               => 0,
            'inherits'            => [],
            'permissions'         => [
                'players.view',
                'analysis.view',
                'marketplace.browse',
                'markt.browse',
            ],
            'registerable'        => false,
            'home_route'          => 'home',
            'dashboard_redirect'  => 'home',
        ],
    ],

    /** Roles offered on the public registration form. */
    'public_register' => ['player', 'club', 'scout', 'trainer', 'fan', 'provider'],

    /** Roles that only super_admin may assign. */
    'elevated_roles' => ['super_admin', 'admin'],

    /**
     * Optional: permission also requires an active membership feature (FIT-Pass).
     * Role permission must pass first; then membership feature is checked.
     */
    'membership_gated_permissions' => [
        'analysis.regenerate' => 'ai_analysis',
        'crm.access'          => 'crm_lite',
        'crm.manage'          => 'crm_lite',
        'predictions.submit'  => 'predictions',
    ],

    /** Route permission map — enforced by Router dispatch and requirePermission(). */
    'route_permissions' => [
        'admin.dashboard'       => 'admin.access',
        'admin.resource'        => 'admin.access',
        'admin.users'           => 'admin.users.view',
        'admin.users.role'      => 'admin.users.edit',
        'club.dashboard'        => 'club.dashboard',
        'trainer.dashboard'     => 'trainer.dashboard',
        'trainers.index'        => 'players.view',
        'scout.dashboard'       => 'scout.dashboard',
        'scout.players.create'  => 'scout.manage_players',
        'scout.players.store'   => 'scout.manage_players',
        'scout.players.bulk'    => 'scout.manage_players',
        'scout.players.bulk.store' => 'scout.manage_players',
        'scout.players.link'    => 'scout.manage_players',
        'scout.players.link.store' => 'scout.manage_players',
        'scout.gdpr.accept'     => 'scout.manage_players',
        'scout.players.edit'    => 'scout.manage_players',
        'scout.players.update'  => 'scout.manage_players',
        'scout.players.delete'  => 'scout.manage_players',
        'scout.shortlist.add'   => 'scout.shortlist',
        'scout.shortlist.remove'=> 'scout.shortlist',
        'players.analysis'      => 'analysis.view',
        'players.analysis.regenerate' => 'analysis.regenerate',
        'players.health.store'  => 'analysis.health.manage',
        'admin.players.analysis' => 'admin.access',
        'admin.players.analysis.regenerate' => 'analysis.regenerate',
        'admin.players.health.store' => 'analysis.health.manage',
        'admin.players.health' => 'analysis.health.manage',
        'providers.panel'       => 'provider.panel',
        'providers.join'        => 'provider.join',
        'providers.join.post'   => 'provider.join',
        'admin.crm.dashboard'   => 'crm.access',
        'admin.crm.contacts'    => 'crm.access',
        'admin.crm.contacts.export' => 'crm.access',
        'admin.crm.contacts.new' => 'crm.manage',
        'admin.crm.contacts.store' => 'crm.manage',
        'admin.crm.contacts.show' => 'crm.access',
        'admin.crm.contacts.edit' => 'crm.manage',
        'admin.crm.contacts.update' => 'crm.manage',
        'admin.crm.contacts.activity' => 'crm.manage',
        'admin.crm.campaigns'   => 'crm.access',
        'admin.crm.campaigns.new' => 'crm.manage',
        'admin.crm.campaigns.store' => 'crm.manage',
        'admin.crm.campaigns.edit' => 'crm.manage',
        'admin.crm.campaigns.update' => 'crm.manage',
        'admin.referrals'       => 'referrals.admin',
        'admin.players'         => 'admin.access',
        'admin.players.create'  => 'admin.content',
        'admin.players.store'   => 'admin.content',
        'admin.players.bulk'    => 'admin.content',
        'admin.players.bulk.store' => 'admin.content',
        'admin.players.edit'    => 'admin.content',
        'admin.players.update'  => 'admin.content',
        'admin.players.delete'  => 'admin.content',
        'admin.marketplace'     => 'marketplace.admin',
        'admin.marketplace.vendor.approve' => 'marketplace.admin',
        'admin.marketplace.vendor.suspend' => 'marketplace.admin',
        'admin.marketplace.listing.feature' => 'marketplace.admin',
        'admin.marketplace.listing.archive' => 'marketplace.admin',
        'marketplace.sell'              => 'marketplace.sell',
        'marketplace.sell.post'         => 'marketplace.sell',
        'vendor.dashboard'              => 'marketplace.sell',
        'vendor.listings.create'        => 'marketplace.sell',
        'vendor.listings.store'         => 'marketplace.sell',
        'vendor.listings.edit'          => 'marketplace.sell',
        'vendor.listings.update'        => 'marketplace.sell',
        'vendor.orders'                 => 'marketplace.sell',
        'vendor.orders.status'          => 'marketplace.sell',
        'fans.create'                   => 'fan.create',
        'only_talents.upload'           => 'talent.upload',
        'only_talents.upload.post'      => 'talent.upload',
        'only_talents.subscribe'        => 'profile.edit',
        'only_talents.subscribe.post'   => 'profile.edit',
        'only_talents.like'             => 'profile.edit',
        'bookings.my'                   => 'booking.book',
        'bookings.checkout'             => 'booking.book',
        'bookings.checkout.place'       => 'booking.book',
        'bookings.provider'             => 'booking.offer',
        'bookings.provider.profile'     => 'booking.offer',
        'bookings.provider.slot.add'    => 'booking.offer',
        'bookings.provider.slot.delete' => 'booking.offer',
        'bookings.provider.orders'      => 'booking.offer',
        'bookings.provider.confirm'     => 'booking.offer',
        'bookings.provider.cancel'      => 'booking.offer',
        'admin.bookings'                => 'booking.admin',
        'admin.bookings.verify'         => 'booking.admin',
        'pro_coaches.feed'              => 'pro_coaches.subscribe',
        'pro_coaches.my_sessions'       => 'pro_coaches.book',
        'pro_coaches.subscribe'         => 'pro_coaches.subscribe',
        'pro_coaches.subscribe.post'    => 'pro_coaches.subscribe',
        'pro_coaches.book'              => 'pro_coaches.book',
        'pro_coaches.book.post'         => 'pro_coaches.book',
        'pro_coaches.become'            => 'profile.edit',
        'pro_coaches.become.post'       => 'profile.edit',
        'pro_coaches.dashboard'         => 'pro_coaches.dashboard',
        'pro_coaches.dashboard.profile' => 'pro_coaches.dashboard',
        'pro_coaches.dashboard.tier'    => 'pro_coaches.dashboard',
        'pro_coaches.dashboard.tier.delete' => 'pro_coaches.dashboard',
        'pro_coaches.dashboard.post'    => 'pro_coaches.dashboard',
        'pro_coaches.dashboard.offering'=> 'pro_coaches.dashboard',
        'pro_coaches.dashboard.offering.delete' => 'pro_coaches.dashboard',
        'pro_coaches.dashboard.slot.add'=> 'pro_coaches.dashboard',
        'pro_coaches.dashboard.slot.delete' => 'pro_coaches.dashboard',
        'admin.pro_coaches'             => 'pro_coaches.admin',
        'admin.pro_coaches.approve'     => 'pro_coaches.admin',
        'admin.pro_coaches.feature'     => 'pro_coaches.admin',
        'admin.pro_coaches.moderate'    => 'pro_coaches.admin',
        'transfer_bureau.profile'       => 'transfer_bureau.seek',
        'transfer_bureau.profile.update'=> 'transfer_bureau.seek',
        'transfer_bureau.listings.create' => 'transfer_bureau.list',
        'transfer_bureau.listings.store'  => 'transfer_bureau.list',
        'transfer_bureau.trials'        => 'transfer_bureau.access',
        'transfer_bureau.trials.store'  => 'transfer_bureau.access',
        'transfer_bureau.trials.respond'=> 'transfer_bureau.access',
        'transfer_bureau.contact'       => 'transfer_bureau.access',
        'transfer_bureau.premium.checkout' => 'transfer_bureau.access',
        'admin.transfer_bureau'         => 'transfer_bureau.admin',
        'admin.transfer_bureau.verify'  => 'transfer_bureau.admin',
        'admin.transfer_bureau.moderate'=> 'transfer_bureau.admin',
        'admin.memberships'         => 'membership.manage',
        'admin.memberships.assign'  => 'membership.manage',
        'admin.memberships.legacy'  => 'membership.manage',
        'admin.memberships.assign.legacy' => 'membership.manage',
        'admin.talent_categories'   => 'admin.access',
        'admin.talent_categories.create' => 'admin.access',
        'admin.talent_categories.store'  => 'admin.access',
        'admin.talent_categories.edit'   => 'admin.access',
        'admin.talent_categories.update' => 'admin.access',
        'admin.talent_categories.delete' => 'admin.access',
        'admin.discovery'           => 'admin.access',
        'admin.discovery.toggle'    => 'admin.access',
        'admin.discovery.weights'   => 'admin.access',
        'membership.index'          => 'profile.edit',
        'membership.role'           => 'profile.edit',
        'membership.checkout'       => 'profile.edit',
        'membership.process'        => 'profile.edit',
        'membership.account'        => 'profile.edit',
        'membership.usage'          => 'profile.edit',
        'membership.cancel'         => 'profile.edit',
        'membership.trial'          => 'profile.edit',
        'wellness.dashboard'        => 'wellness.access',
        'wellness.goals'            => 'wellness.access',
        'wellness.goals.save'       => 'wellness.access',
        'wellness.recommendations'  => 'wellness.access',
        'wellness.chat'             => 'wellness.access',
        'wellness.chat.post'        => 'wellness.access',
        'wellness.calendar'         => 'wellness.access',
        'wellness.calendar.google'  => 'wellness.access',
        'wellness.calendar.google.callback' => 'wellness.access',
        'wellness.calendar.disconnect' => 'wellness.access',
        'wellness.booking.prepare'  => 'wellness.access',
        'wellness.booking.confirm'  => 'wellness.access',
    ],
];
